package com.utms.entity;
// Generated 6 Jun, 2015 5:49:38 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExeConfig generated by hbm2java
 */
@Entity
@Table(name="ExeConfig"
    ,catalog="utms_latestV1"
)
public class ExeConfig  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private String runId;
     private String url;
     private String name;
     private Set<ExeRun> exeRuns = new HashSet<ExeRun>(0);
     private Set<RefOperatingSystem> refOperatingSystems = new HashSet<RefOperatingSystem>(0);
     private Set<RefBrowser> refBrowsers = new HashSet<RefBrowser>(0);
     private Set<AutoTestCase> autoTestCases = new HashSet<AutoTestCase>(0);

    public ExeConfig() {
    }

    public ExeConfig(Project project, String runId, String url, String name, Set<ExeRun> exeRuns, Set<RefOperatingSystem> refOperatingSystems, Set<RefBrowser> refBrowsers, Set<AutoTestCase> autoTestCases) {
       this.project = project;
       this.runId = runId;
       this.url = url;
       this.name = name;
       this.exeRuns = exeRuns;
       this.refOperatingSystems = refOperatingSystems;
       this.refBrowsers = refBrowsers;
       this.autoTestCases = autoTestCases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id")
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    
    @Column(name="runId", length=45)
    public String getRunId() {
        return this.runId;
    }
    
    public void setRunId(String runId) {
        this.runId = runId;
    }

    
    @Column(name="url", length=45)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exeConfig")
    public Set<ExeRun> getExeRuns() {
        return this.exeRuns;
    }
    
    public void setExeRuns(Set<ExeRun> exeRuns) {
        this.exeRuns = exeRuns;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ExeConfigRefOS", catalog="utms_latestV1", joinColumns = { 
        @JoinColumn(name="exeConfig_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="refOperatingSystem_id", nullable=false, updatable=false) })
    public Set<RefOperatingSystem> getRefOperatingSystems() {
        return this.refOperatingSystems;
    }
    
    public void setRefOperatingSystems(Set<RefOperatingSystem> refOperatingSystems) {
        this.refOperatingSystems = refOperatingSystems;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ExeConfigRefBrowser", catalog="utms_latestV1", joinColumns = { 
        @JoinColumn(name="exeConfig_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="refBrowser_id", nullable=false, updatable=false) })
    public Set<RefBrowser> getRefBrowsers() {
        return this.refBrowsers;
    }
    
    public void setRefBrowsers(Set<RefBrowser> refBrowsers) {
        this.refBrowsers = refBrowsers;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ExeConfigAutoTestCase", catalog="utms_latestV1", joinColumns = { 
        @JoinColumn(name="exeConfig_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="autoTestCase_id", nullable=false, updatable=false) })
    public Set<AutoTestCase> getAutoTestCases() {
        return this.autoTestCases;
    }
    
    public void setAutoTestCases(Set<AutoTestCase> autoTestCases) {
        this.autoTestCases = autoTestCases;
    }




}


