package com.utms.entity;
// Generated 9 Jun, 2015 3:30:57 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExeConfigRefOsRefBrowser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="ExeConfigRefOsRefBrowser"
    ,catalog="utms_latestV2"
)
public class ExeConfigRefOsRefBrowser  implements java.io.Serializable {


     private Integer id;
     private RefOsRefBrowser refOsRefBrowser;
     private ExeConfig exeConfig;
     private Set<ExeRun> exeRuns = new HashSet<ExeRun>(0);

    public ExeConfigRefOsRefBrowser() {
    }

    public ExeConfigRefOsRefBrowser(RefOsRefBrowser refOsRefBrowser, ExeConfig exeConfig, Set<ExeRun> exeRuns) {
       this.refOsRefBrowser = refOsRefBrowser;
       this.exeConfig = exeConfig;
       this.exeRuns = exeRuns;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="refOsRefBrowser_id")
    public RefOsRefBrowser getRefOsRefBrowser() {
        return this.refOsRefBrowser;
    }
    
    public void setRefOsRefBrowser(RefOsRefBrowser refOsRefBrowser) {
        this.refOsRefBrowser = refOsRefBrowser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exeConfig_id")
    public ExeConfig getExeConfig() {
        return this.exeConfig;
    }
    
    public void setExeConfig(ExeConfig exeConfig) {
        this.exeConfig = exeConfig;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exeConfigRefOsRefBrowser")
    public Set<ExeRun> getExeRuns() {
        return this.exeRuns;
    }
    
    public void setExeRuns(Set<ExeRun> exeRuns) {
        this.exeRuns = exeRuns;
    }



}


