package com.utms.entity;
// Generated 9 Jun, 2015 3:30:57 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ExeConfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="ExeConfig"
    ,catalog="utms_latestV2"
)
public class ExeConfig  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private RefUrl refUrl;
     private String runId;
     private String name;
     private Set<AutoTestCase> autoTestCases = new HashSet<AutoTestCase>(0);
     private Set<ExeConfigRefOsRefBrowser> exeConfigRefOsRefBrowsers = new HashSet<ExeConfigRefOsRefBrowser>(0);

    public ExeConfig() {
    }

    public ExeConfig(Project project, RefUrl refUrl, String runId, String name, Set<AutoTestCase> autoTestCases, Set<ExeConfigRefOsRefBrowser> exeConfigRefOsRefBrowsers) {
       this.project = project;
       this.refUrl = refUrl;
       this.runId = runId;
       this.name = name;
       this.autoTestCases = autoTestCases;
       this.exeConfigRefOsRefBrowsers = exeConfigRefOsRefBrowsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id")
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="refUrl_id")
    public RefUrl getRefUrl() {
        return this.refUrl;
    }
    
    public void setRefUrl(RefUrl refUrl) {
        this.refUrl = refUrl;
    }

    
    @Column(name="runId", length=45)
    public String getRunId() {
        return this.runId;
    }
    
    public void setRunId(String runId) {
        this.runId = runId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ExeConfigAutoTestCase", catalog="utms_latestV2", joinColumns = { 
        @JoinColumn(name="exeConfig_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="autoTestCase_id", nullable=false, updatable=false) })
    public Set<AutoTestCase> getAutoTestCases() {
        return this.autoTestCases;
    }
    
    public void setAutoTestCases(Set<AutoTestCase> autoTestCases) {
        this.autoTestCases = autoTestCases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exeConfig")
    public Set<ExeConfigRefOsRefBrowser> getExeConfigRefOsRefBrowsers() {
        return this.exeConfigRefOsRefBrowsers;
    }
    
    public void setExeConfigRefOsRefBrowsers(Set<ExeConfigRefOsRefBrowser> exeConfigRefOsRefBrowsers) {
        this.exeConfigRefOsRefBrowsers = exeConfigRefOsRefBrowsers;
    }




}


