package com.utms.entity;
// Generated 6 Jun, 2015 5:49:38 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExeRun generated by hbm2java
 */
@Entity
@Table(name="ExeRun"
    ,catalog="utms_latestV1"
)
public class ExeRun  implements java.io.Serializable {


     private Integer id;
     private ExeConfig exeConfig;
     private Date startDateTime;
     private Date endDateTime;
     private Set<TestCaseResults> testCaseResultses = new HashSet<TestCaseResults>(0);

    public ExeRun() {
    }

    public ExeRun(ExeConfig exeConfig, Date startDateTime, Date endDateTime, Set<TestCaseResults> testCaseResultses) {
       this.exeConfig = exeConfig;
       this.startDateTime = startDateTime;
       this.endDateTime = endDateTime;
       this.testCaseResultses = testCaseResultses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exeConfig_id")
    public ExeConfig getExeConfig() {
        return this.exeConfig;
    }
    
    public void setExeConfig(ExeConfig exeConfig) {
        this.exeConfig = exeConfig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startDateTime", length=10)
    public Date getStartDateTime() {
        return this.startDateTime;
    }
    
    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="endDateTime", length=10)
    public Date getEndDateTime() {
        return this.endDateTime;
    }
    
    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exeRun")
    public Set<TestCaseResults> getTestCaseResultses() {
        return this.testCaseResultses;
    }
    
    public void setTestCaseResultses(Set<TestCaseResults> testCaseResultses) {
        this.testCaseResultses = testCaseResultses;
    }




}


