package com.utms.entity;
// Generated 3 Jun, 2015 12:49:41 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="Module")
public class Module  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private String name;
     private String description;
     private Set<ObjectRepo> objectRepos = new HashSet<ObjectRepo>(0);
     private Set<AutoTestCase> autoTestCases = new HashSet<AutoTestCase>(0);
     private Set<TestCase> testCases = new HashSet<TestCase>(0);

    public Module() {
    }

    public Module(Project project, String name, String description, Set<ObjectRepo> objectRepos, Set<AutoTestCase> autoTestCases, Set<TestCase> testCases) {
       this.project = project;
       this.name = name;
       this.description = description;
       this.objectRepos = objectRepos;
       this.autoTestCases = autoTestCases;
       this.testCases = testCases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="project_id")
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<ObjectRepo> getObjectRepos() {
        return this.objectRepos;
    }
    
    public void setObjectRepos(Set<ObjectRepo> objectRepos) {
        this.objectRepos = objectRepos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<AutoTestCase> getAutoTestCases() {
        return this.autoTestCases;
    }
    
    public void setAutoTestCases(Set<AutoTestCase> autoTestCases) {
        this.autoTestCases = autoTestCases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<TestCase> getTestCases() {
        return this.testCases;
    }
    
    public void setTestCases(Set<TestCase> testCases) {
        this.testCases = testCases;
    }




}


