package com.utms.entity;
// Generated 9 Jun, 2015 3:30:57 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ObjectRepo generated by hbm2java
 */
@Entity
@Table(name="ObjectRepo"
    ,catalog="utms_latestV2"
)
public class ObjectRepo  implements java.io.Serializable {


     private Integer id;
     private Module module;
     private String name;
     private String description;
     private Boolean isReusable;
     private Set<Object> objects = new HashSet<Object>(0);

    public ObjectRepo() {
    }

    public ObjectRepo(Module module, String name, String description, Boolean isReusable, Set<Object> objects) {
       this.module = module;
       this.name = name;
       this.description = description;
       this.isReusable = isReusable;
       this.objects = objects;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="module_id")
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="isReusable")
    public Boolean getIsReusable() {
        return this.isReusable;
    }
    
    public void setIsReusable(Boolean isReusable) {
        this.isReusable = isReusable;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="objectRepo")
    public Set<Object> getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set<Object> objects) {
        this.objects = objects;
    }




}


