package com.utms.entity;
// Generated 3 Jun, 2015 12:49:41 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * RefBrowser generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="RefBrowser"
    ,catalog="utms_latest"
)
public class RefBrowser  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<ExeConfig> exeConfigs = new HashSet<ExeConfig>(0);

    public RefBrowser() {
    }

    public RefBrowser(String name, Set<ExeConfig> exeConfigs) {
       this.name = name;
       this.exeConfigs = exeConfigs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="ExeConfigRefBrowser", catalog="utms_latest", joinColumns = { 
        @JoinColumn(name="refBrowser_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="exeConfig_id", nullable=false, updatable=false) })
    public Set<ExeConfig> getExeConfigs() {
        return this.exeConfigs;
    }
    
    public void setExeConfigs(Set<ExeConfig> exeConfigs) {
        this.exeConfigs = exeConfigs;
    }




}


