package com.utms.entity;
// Generated 3 Jun, 2015 12:49:41 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefObjectType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="RefObjectType")
public class RefObjectType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Object> objects = new HashSet<Object>(0);

    public RefObjectType() {
    }

    public RefObjectType(String name, Set<Object> objects) {
       this.name = name;
       this.objects = objects;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="refObjectType")
    public Set<Object> getObjects() {
        return this.objects;
    }
    
    public void setObjects(Set<Object> objects) {
        this.objects = objects;
    }




}


