package com.utms.entity;
// Generated 3 Jun, 2015 12:49:41 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefTestPriority generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="RefTestPriority"
    ,catalog="utms_latest"
)
public class RefTestPriority  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<TestCase> testCases = new HashSet<TestCase>(0);

    public RefTestPriority() {
    }

    public RefTestPriority(String name, Set<TestCase> testCases) {
       this.name = name;
       this.testCases = testCases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="refTestPriority")
    public Set<TestCase> getTestCases() {
        return this.testCases;
    }
    
    public void setTestCases(Set<TestCase> testCases) {
        this.testCases = testCases;
    }




}


