package com.utms.entity;
// Generated 9 Jun, 2015 3:30:57 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestStep generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="TestStep"
    ,catalog="utms_latestV2"
)
public class TestStep  implements java.io.Serializable {


     private Integer id;
     private String value;
     private Set<AllSteps> allStepses = new HashSet<AllSteps>(0);

    public TestStep() {
    }

    public TestStep(String value, Set<AllSteps> allStepses) {
       this.value = value;
       this.allStepses = allStepses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="value", length=45)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testStep")
    public Set<AllSteps> getAllStepses() {
        return this.allStepses;
    }
    
    public void setAllStepses(Set<AllSteps> allStepses) {
        this.allStepses = allStepses;
    }




}


