package com.utms.entity;
// Generated 3 Jun, 2015 12:49:41 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestStep generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="TestStep")
public class TestStep  implements java.io.Serializable {


     private Integer id;
     private TestCase testCase;
     private String stepNum;
     private String value;
     private Set<AllSteps> allStepses = new HashSet<AllSteps>(0);
     private Set<AutoTestStep> autoTestSteps = new HashSet<AutoTestStep>(0);

    public TestStep() {
    }

    public TestStep(TestCase testCase, String stepNum, String value, Set<AllSteps> allStepses, Set<AutoTestStep> autoTestSteps) {
       this.testCase = testCase;
       this.stepNum = stepNum;
       this.value = value;
       this.allStepses = allStepses;
       this.autoTestSteps = autoTestSteps;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="testCase_id")
    public TestCase getTestCase() {
        return this.testCase;
    }
    
    public void setTestCase(TestCase testCase) {
        this.testCase = testCase;
    }

    
    @Column(name="stepNum", length=45)
    public String getStepNum() {
        return this.stepNum;
    }
    
    public void setStepNum(String stepNum) {
        this.stepNum = stepNum;
    }

    
    @Column(name="value", length=45)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testStep")
    public Set<AllSteps> getAllStepses() {
        return this.allStepses;
    }
    
    public void setAllStepses(Set<AllSteps> allStepses) {
        this.allStepses = allStepses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testStep")
    public Set<AutoTestStep> getAutoTestSteps() {
        return this.autoTestSteps;
    }
    
    public void setAutoTestSteps(Set<AutoTestStep> autoTestSteps) {
        this.autoTestSteps = autoTestSteps;
    }




}


