package com.utms.entity;
// Generated 9 Jun, 2015 3:30:57 PM by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestCaseResults generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="TestCaseResults"
    ,catalog="utms_latestV2"
)
public class TestCaseResults  implements java.io.Serializable {


     private Integer id;
     private ExeRun exeRun;
     private AutoTestCase autoTestCase;
     private String result;
     private String errorReason;
     private Date startDateTime;
     private Date endDateTime;
     private Set<TestStepResults> testStepResultses = new HashSet<TestStepResults>(0);

    public TestCaseResults() {
    }

    public TestCaseResults(ExeRun exeRun, AutoTestCase autoTestCase, String result, String errorReason, Date startDateTime, Date endDateTime, Set<TestStepResults> testStepResultses) {
       this.exeRun = exeRun;
       this.autoTestCase = autoTestCase;
       this.result = result;
       this.errorReason = errorReason;
       this.startDateTime = startDateTime;
       this.endDateTime = endDateTime;
       this.testStepResultses = testStepResultses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exeRun_id")
    public ExeRun getExeRun() {
        return this.exeRun;
    }
    
    public void setExeRun(ExeRun exeRun) {
        this.exeRun = exeRun;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="autoTestcase_id")
    public AutoTestCase getAutoTestCase() {
        return this.autoTestCase;
    }
    
    public void setAutoTestCase(AutoTestCase autoTestCase) {
        this.autoTestCase = autoTestCase;
    }

    
    @Column(name="result", length=100)
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }

    
    @Column(name="errorReason", length=100)
    public String getErrorReason() {
        return this.errorReason;
    }
    
    public void setErrorReason(String errorReason) {
        this.errorReason = errorReason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startDateTime", length=10)
    public Date getStartDateTime() {
        return this.startDateTime;
    }
    
    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="endDateTime", length=10)
    public Date getEndDateTime() {
        return this.endDateTime;
    }
    
    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="testCaseResults")
    public Set<TestStepResults> getTestStepResultses() {
        return this.testStepResultses;
    }
    
    public void setTestStepResultses(Set<TestStepResults> testStepResultses) {
        this.testStepResultses = testStepResultses;
    }

	@Override
	public String toString() {
		return "TestCaseResults [id=" + id + ", exeRun=" + exeRun
				+ ", autoTestCase=" + autoTestCase + ", result=" + result
				+ ", errorReason=" + errorReason + ", startDateTime="
				+ startDateTime + ", endDateTime=" + endDateTime
				+ ", testStepResultses=" + testStepResultses + "]";
	}




}


