package com.utms.actions;


public class Action {


	public enum Types {
		ACCEPTALERT, CHECK, UNCHECK, CLEARSESSION, CLICK, CLOSEBROWSER, CLOSEDRIVER,CLEAR,
		ENTER, OPENURL, MOUSEOVER, GOBACK, KEYPRESS, SELECTBYINDEX,SELECTBYVALUE,
		SELECTBYVISIBLETEXT,SELECTRANDOMLY, SELECTFRAMEBYINDEX, SELECTFRAMEBYXPATH, 
		WAIT, SELECTWINDOW, VERIFYISPRESENT, 
		WAITFORELEMENT, DRAGANDDROP, REFRESH
	}

	public static Types getActionTypeByString(String action) {
		return Types.valueOf(action.toUpperCase());
	}

}
